import samsung1 from "../assets/S25ULTRA.jpg";
// import samsung2 from "./assets/none.jpg";
import iphone1 from "../assets/15PRO.png";
import redmi1 from "../assets/redminote14.png";
import pc5 from "../assets/RX3I5bViXa5VL5q2I3h4UlHmlUnianu3RJLG0H99inmN63k2CJ0pxJX168UZ.jpg";
import a55 from "../assets/Q9wpNk3gCNJqrUEaCezb3NfbH2ofrzoXn9JqKr0okO9hzQyb7eH72YdGXXWL.png";
import a16 from "../assets/EnjU7GMsChOXUpHD9ahCHcv5eDIqgqyMbeILgSmEDSeMYQcd8Vezl1MX0Xwr.png";
import Deklor from "../assets/ZuWzlSxj6b5Ja4qqV5X1FwIGLLZUdcqSlW9OAvXYOp0KTeP6kGlixI5tZFsL.jpg";
import Radar from "../assets/9GixDqSvMzkVbc1G5qmekNtUVCpJmVAf83pXMl6DfLVB3FOSPDpCvnOYqgsC.jpg";
// import  from "..";

export const Cards = [
    {
        id: 1,
        brand: "Samsung",
        model: "S25 Ultra",
        storage: "256GB, 512GB, 1TB",
        price: "1200$",
        color: "black",
        avatar1: samsung1,
        dimensions: "159.9 x 76.7 x 8.25 mm",
        faceID: "Mavjud",
        weight: "221 g",
        osVersion: "iOS 17",
        protection: "IP68",
    },
    {
        id: 2,
        brand: "Apple",
        model: "Iphone 15 Pro",
        storage: "256GB, 512GB, 1TB",
        price: "1600$",
        color: "black",
        avatar1: iphone1,
        dimensions: "146.7 x 71.5 x 7.4 mm",
        faceID: "Mavjud",
        weight: "187 g",
        osVersion: "iOS 17",
        protection: "IP68",
    },
    {
        id: 3,
        brand: "Xiaomi",
        model: "Redmi Note 14 Pro",
        storage: "256GB, 512GB, 1TB",
        price: "1000$",
        color: "black",
        avatar1: redmi1,
        dimensions: "164.6 x 76.1 x 8.1 mm",
        faceID: "Mavjud",
        weight: "204 g",
        osVersion: "Android 12",
        protection: "IP53",
    },
    {
        id: 4,
        brand: "Ps",
        model: "Sony PlayStation PS5 Edition 1TB",
        storage: "1TB",
        price: "6000$",
        color: "white",
        avatar1: pc5,
        dimensions: "390 x 104 x 260 mm",
        faceID: "Yo'q",
        weight: "4.5 kg",
        osVersion: "PlayStation OS",
        protection: "Yo'q",
    },
    {
        id: 5,
        brand: "Samsung",
        model: "Samsung A55",
        storage: "256GB, 512GB, 1TB",
        price: "4000$",
        color: "white",
        avatar1: a55,
        dimensions: "159.9 x 76.7 x 8.25 mm",
        faceID: "Mavjud",
        weight: "221 g",
        osVersion: "Android 13",
        protection: "IP68",
    },
    {
        id: 6,
        brand: "Samsung",
        model: "Samsung A16",
        storage: "256GB, 512GB, 1TB",
        price: "300$",
        color: "black",
        avatar1: a16,
        dimensions: "160 x 75 x 8.9 mm",
        faceID: "Yo'q",
        weight: "190 g",
        osVersion: "Android 11",
        protection: "Yo'q",
    },
    {
        id: 7,
        brand: "Deklor",
        model: "Deklor Battery",
        storage: "60 A/H",
        price: "80$",
        color: "black/black",
        avatar1: Deklor,
        dimensions: "180 x 90 x 70 mm",
        faceID: "Yo'q",
        weight: "1.2 kg",
        osVersion: "Yo'q",
        protection: "Yo'q",
    },
    {
        id: 8,
        brand: "Detector",
        model: "Radar-Detector",
        storage: "",
        price: "200$",
        color: "black",
        avatar1: Radar,
        dimensions: "120 x 60 x 30 mm",
        faceID: "Yo'q",
        weight: "250 g",
        osVersion: "Yo'q",
        protection: "Yo'q",
    },
    {
        id: 9,
        brand: "Airpods",
        model: "Sony PlayStation PS5 Edition 1TB",
        storage: "256GB, 512GB, 1TB",
        price: "6000$",
        color: "white",
        avatar1: pc5,
        dimensions: "390 x 104 x 260 mm",
        faceID: "Yo'q",
        weight: "4.5 kg",
        osVersion: "PlayStation OS",
        protection: "Yo'q",
    },
    {
        id: 10,
        brand: "Samsung",
        model: "Samsung A55",
        storage: "256GB, 512GB, 1TB",
        price: "4000$",
        color: "white",
        avatar1: a55,
        dimensions: "159.9 x 76.7 x 8.25 mm",
        faceID: "Mavjud",
        weight: "221 g",
        osVersion: "Android 13",
        protection: "IP68",
    },
    {
        id: 11,
        brand: "Samsung",
        model: "S25 Ultra",
        storage: "256GB, 512GB, 1TB",
        price: "1200$",
        color: "black",
        avatar1: samsung1,
        dimensions: "159.9 x 76.7 x 8.25 mm",
        faceID: "Mavjud",
        weight: "221 g",
        osVersion: "iOS 17",
        protection: "IP68",
    },
    {
        id: 12,
        brand: "Apple",
        model: "Iphone 15 Pro",
        storage: "256GB, 512GB, 1TB",
        price: "1600$",
        color: "black",
        avatar1: iphone1,
        dimensions: "146.7 x 71.5 x 7.4 mm",
        faceID: "Mavjud",
        weight: "187 g",
        osVersion: "iOS 17",
        protection: "IP68",
    },
    {
        id: 13,
        brand: "Xiaomi",
        model: "Redmi Note 14 Pro",
        storage: "256GB, 512GB, 1TB",
        price: "1000$",
        color: "black",
        avatar1: redmi1,
        dimensions: "164.6 x 76.1 x 8.1 mm",
        faceID: "Mavjud",
        weight: "204 g",
        osVersion: "Android 12",
        protection: "IP53",
    },
    {
        id: 14,
        brand: "Ps",
        model: "Sony PlayStation PS5 Edition 1TB",
        storage: "1TB",
        price: "6000$",
        color: "white",
        avatar1: pc5,
        dimensions: "390 x 104 x 260 mm",
        faceID: "Yo'q",
        weight: "4.5 kg",
        osVersion: "PlayStation OS",
        protection: "Yo'q",
    },
    {
        id: 15,
        brand: "Samsung",
        model: "Samsung A55",
        storage: "256GB, 512GB, 1TB",
        price: "4000$",
        color: "white",
        avatar1: a55,
        dimensions: "159.9 x 76.7 x 8.25 mm",
        faceID: "Mavjud",
        weight: "221 g",
        osVersion: "Android 13",
        protection: "IP68",
    },
    {
        id: 16,
        brand: "Samsung",
        model: "S25 Ultra",
        storage: "256GB, 512GB, 1TB",
        price: "1200$",
        color: "black",
        avatar1: samsung1,
        dimensions: "159.9 x 76.7 x 8.25 mm",
        faceID: "Mavjud",
        weight: "221 g",
        osVersion: "iOS 17",
        protection: "IP68",
    },
    {
        id: 17,
        brand: "Apple",
        model: "Iphone 15 Pro",
        storage: "256GB, 512GB, 1TB",
        price: "1600$",
        color: "black",
        avatar1: iphone1,
        dimensions: "146.7 x 71.5 x 7.4 mm",
        faceID: "Mavjud",
        weight: "187 g",
        osVersion: "iOS 17",
        protection: "IP68",
    },
    {
        id: 18,
        brand: "Xiaomi",
        model: "Redmi Note 14 Pro",
        storage: "256GB, 512GB, 1TB",
        price: "1000$",
        color: "black",
        avatar1: redmi1,
        dimensions: "164.6 x 76.1 x 8.1 mm",
        faceID: "Mavjud",
        weight: "204 g",
        osVersion: "Android 12",
        protection: "IP53",
    },
    {
        id: 19,
        brand: "Ps",
        model: "Sony PlayStation PS5 Edition 1TB",
        storage: "1TB",
        price: "6000$",
        color: "white",
        avatar1: pc5,
        dimensions: "390 x 104 x 260 mm",
        faceID: "Yo'q",
        weight: "4.5 kg",
        osVersion: "PlayStation OS",
        protection: "Yo'q",
    },
    {
        id: 20,
        brand: "Samsung",
        model: "Samsung A55",
        storage: "256GB, 512GB, 1TB",
        price: "4000$",
        color: "white",
        avatar1: a55,
        dimensions: "159.9 x 76.7 x 8.25 mm",
        faceID: "Mavjud",
        weight: "221 g",
        osVersion: "Android 13",
        protection: "IP68",
    },
];

